export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNOUT = 'AUTH_SIGNOUT_SUCCESS';

export const NOTIFY_INFO = 'NOTIFY_INFO';
export const NOTIFY_SUCCESS = 'NOTIFY_SUCCESS';
export const NOTIFY_ERROR = 'NOTIFY_ERROR';
export const NOTIFY_WARNING = 'NOTIFY_WARNING';
